name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  lint:
    name: HLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HLint repo
        uses: actions/checkout@v2
        with:
          repository: ndmitchell/hlint
          ref: '8e10b5143acf97fbdf9baff40ee2da93881e0bf8'
      - name: Set up Haskell
        id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.0.1'
          cabal-version: 'latest'
      - name: Configure HLint
        run: cabal new-configure
      - name: Freeze HLint
        run: cabal freeze
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ hashFiles('cabal.project.freeze') }}
      - name: Build HLint
        run: cabal new-install
      - name: Checkout text-display
        uses: actions/checkout@v2
        with:
          path: ./text-display
      - name: Run HLint
        run: |
          cd text-display && find src test -name "*.hs" -exec ${{ steps.setup-haskell.outputs.cabal-store }}/../bin/hlint {} + 
  native:
    name: ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ghc: ['8.8.4', '8.10.7', '9.0.1', '9.2.1']
        exclude:
          - os: windows-latest
            ghc: '9.2.1'
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Set up Haskell
        id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 'latest'
      - name: Configure
        run: cabal new-configure --enable-tests
      - name: Freeze
        run: cabal freeze
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-
      - name: Build
        run: cabal new-build
      - name: Test
        run: cabal new-test all
