name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  native:
    name: ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ghc: ['8.8.4', '8.10.7', '9.0.1', '9.2.1']
        exclude:
          - os: windows-latest
            ghc: '9.2.1'
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Set up Haskell
        id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 'latest'
      - name: Get dependencies
        run: |
          sudo apt-get update -q -y
          sudo apt-get install hlint
      - name: Freeze
        run: cabal freeze
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.haskell-setup.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-
      - name: Run HLint
        run: ./github/workflows/hlint-runner.sh
      - name: Configure
        run: cabal new-configure -w ${{ steps.haskell-setup.outputs.ghc-exe }}
      - name: Build
        run: cabal new-build
      - name: Test
        run: cabal new-test all
  emulated:
    name: ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['aarch64', 'armv7', 'ppc64le']
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Build and test
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: ${{ matrix.arch }}
          distro: bullseye
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -q -y ghc cabal-install hlint
          run: |
            cabal new-update
            ./.github/workflows/hlint-runner.sh
            cabal new-build
            cabal new-test all
